version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: my_db
    volumes:
      - mongo-data:/data/db

  mongo-express:
    container_name: mongo_ui
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: abc
    depends_on:
      - mongo

  app:
    container_name: app
    build: ./
    # image: shubhamsaxena2207/fastapi-app:latest
    ports: 
      - 5000:5000
    environment: 
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local

